import { BeneficiaryCase } from '@/types/beneficiary';
import { calculateTotalScore, calculateZakatEligibility } from '../scoring/scoringEngine';
import { INBPI_POLICY_V01 } from '../policy/scoringPolicy';
import { DEFAULT_ZAKAT_POLICY } from '../policy/zakatPolicy';

function createSampleCase(
  base: Omit<BeneficiaryCase, 'calculatedScore' | 'zakat' | 'reassessmentHistory'> & {
    zakat: BeneficiaryCase['zakat'];
    reassessmentHistory?: BeneficiaryCase['reassessmentHistory'];
  }
): BeneficiaryCase {
  const calculatedZakat = calculateZakatEligibility(base.zakat, DEFAULT_ZAKAT_POLICY);
  const calculatedScore = calculateTotalScore(
    {
      ...base,
      zakat: calculatedZakat,
      reassessmentHistory: base.reassessmentHistory || [],
    },
    INBPI_POLICY_V01
  );

  return {
    ...base,
    reassessmentHistory: base.reassessmentHistory || [],
    zakat: calculatedZakat,
    calculatedScore,
  };
}

export const SAMPLE_CASES: BeneficiaryCase[] = [
  // 1. Fatima Bi - Low-income widow with 3 children, severe food insecurity & fee arrears
  createSampleCase({
    id: 'IAN-2026-1001',
    beneficiaryCode: 'BEN-1001',
    fullName: 'Fatima Bi',
    dateOfBirth: '1989-04-12',
    calculatedAge: 37,
    gender: 'Female',
    phone: '+91 98451 22301',
    alternatePhone: '+91 98451 22302',
    address: 'H.No 14/2, 3rd Cross, Padarayanapura',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560026',
    caseType: 'widow',
    title: 'Widow with 3 dependent schoolchildren facing severe food shortage and fee eviction',
    narrativeDescription:
      'Fatima lost her husband to cardiac arrest 8 months ago. She does home tailoring earning ₹4,500/month. She has three children aged 7, 10, and 13. Landlord has issued a 15-day eviction warning for 3 months rent arrears, and the school has warned the children will not be allowed for quarterly examinations due to outstanding tuition fees.',
    requestedAmount: 38000,
    minimumEffectiveAmount: 22000,
    verifiedRequirement: 38000,
    fundEligibility: ['Zakat', 'General Welfare', 'Education'],
    status: 'Ready for Decision',
    isDemoCase: true,
    createdAt: '2026-09-18T10:30:00Z',
    updatedAt: '2026-10-02T14:15:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Fatima Bi',
        relationship: 'Self',
        age: 37,
        gender: 'Female',
        employmentStatus: 'Daily Wage',
        monthlyIncome: 4500,
        hasDisability: false,
        isDependent: false,
      },
      {
        id: 'hh-2',
        name: 'Amina Khatoon',
        relationship: 'Daughter',
        age: 13,
        gender: 'Female',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
        educationStatus: 'Class 8',
      },
      {
        id: 'hh-3',
        name: 'Mohammed Bilal',
        relationship: 'Son',
        age: 10,
        gender: 'Male',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
        educationStatus: 'Class 5',
      },
      {
        id: 'hh-4',
        name: 'Zainab Bi',
        relationship: 'Daughter',
        age: 7,
        gender: 'Female',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
        educationStatus: 'Class 2',
      },
    ],
    financial: {
      dependableMonthlyIncome: 4500,
      irregularMonthlyIncome: 800,
      totalHouseholdIncome: 5300,
      perCapitaIncome: 1325,
      incomeStability: 'highly_unstable',
      incomeSources: [
        { id: 'inc-1', source: 'Home Tailoring / Alterations', amount: 4500, earnerName: 'Fatima Bi', isRegular: false },
      ],
      essentialMonthlyExpenses: {
        food: 4200,
        rent: 3500,
        utilities: 800,
        essentialMedicines: 400,
        essentialTransport: 300,
        education: 1800,
        caregiving: 0,
        otherEssential: 500,
        total: 11500,
      },
      liquidAssets: {
        cash: 350,
        bankBalance: 420,
        savings: 0,
        goldSilverValue: 0,
        investments: 0,
        totalLiquid: 770,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 0,
        livestockValue: 0,
        businessAssets: 2500, // old sewing machine
        totalPhysical: 2500,
      },
      debtObligations: {
        totalOutstanding: 21500,
        monthlyDebtPayment: 1000,
        debtType: 'Rent arrears and local provision shop',
        rentArrears: 10500,
        medicalDebt: 6000,
        utilityArrears: 1200,
        foodDebt: 3800,
        essentialEducationDebt: 0,
        consequenceOfNonPayment: 'Landlord verbal eviction notice by end of the month',
      },
      coverageRatio: 0.39,
      reserveMonths: 0.07,
      debtBurdenRatio: 0.22,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: false,
        functionalImpact: 'none',
        requiresCaregiver: false,
        additionalDisabilityExpenses: 0,
      },
      dependencyBurden: {
        totalMembers: 4,
        totalEarners: 1,
        totalDependents: 3,
        childrenCount: 3,
        elderlyCount: 0,
        disabledDependentsCount: 0,
        dependencyRatio: 3.0,
      },
      familyStructure: {
        circumstance: 'single_caregiver',
        category: 'widow',
        widowDetails: {
          yearsSinceSpousePassing: 1,
          familySupportAvailable: false,
          childrenUnderCare: 3,
        },
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 37,
        lifeStage: 'adult',
        createsVulnerability: false,
      },
      chronicCareSafeguarding: {
        hasChronicIllness: false,
        recurringMedicationNeeds: false,
        monthlyMedicationCost: 0,
        safeguardingRisk: 'low',
        abuseNeglectRisk: false,
        unsafeLivingEnvironment: false,
      },
    },
    deprivation: {
      foodSecurity: {
        score: 3,
        mealsPerDay: 2,
        skippedMeals: true,
        daysFoodRemaining: 3,
        childrenAffected: true,
        nutritionalConcerns: 'Mother skips dinner so children can eat rice and dal',
      },
      housingCondition: {
        score: 2,
        type: 'rented_arrears_eviction',
        rentArrearsMonths: 3,
        evictionNoticeReceived: true,
        overcrowded: true,
        weatherExposure: false,
      },
      utilitiesAccess: {
        score: 1,
        electricityAvailable: true,
        cleanWaterAvailable: true,
        cleanCookingFuelAvailable: false,
        adequateSanitationAvailable: true,
      },
      healthAccess: {
        score: 1,
        medicationUnavailable: false,
        treatmentInterruptedDueToCost: false,
        inabilityToAffordEssentialCare: true,
      },
      educationDeprivation: {
        score: 1,
        childrenOutOfSchool: false,
        dropoutRiskDueToFees: true,
        feeArrearsPresent: true,
        examAdmissionBarrier: true,
      },
      otherBasicNeeds: {
        score: 1,
        inadequateClothing: true,
        inadequateHygieneSanitaryAccess: false,
        lackEssentialTransport: false,
        lackCommunicationDevice: false,
      },
    },
    severity: {
      timeUrgency: {
        timeUntilHarm: '1_to_2_weeks',
        points: 6,
      },
      consequenceOfNoAssistance: {
        consequence: 'serious_hardship',
        points: 4,
      },
      essentialityOfIntervention: {
        level: 'essential',
        points: 3,
      },
      expectedBenefit: {
        level: 'meaningful_relief',
        points: 4,
        clinicianInformedNote: 'Clearing rent arrears and school fees protects children from eviction and drop-out.',
      },
      emergencyTrigger: false,
    },
    supportGap: {
      familyCommunitySupport: {
        level: 'no_support',
        points: 3,
        notes: 'Paternal relatives estranged; maternal grandparents deceased',
      },
      governmentOtherSchemes: {
        level: 'applied_pending',
        points: 2,
        schemesChecked: ['Karnataka Widow Pension (Applied, pending tahsildar verification)'],
      },
      remainingFundingGap: {
        verifiedTotalNeed: 38000,
        existingAvailableFunds: 0,
        otherCommittedFunds: 5000,
        requestedFromIlAnNoor: 33000,
        minimumEffectiveAmount: 22000,
        gapRatio: 0.86,
        points: 4,
      },
    },
    caseSpecificData: {
      rentArrearsAmount: 10500,
      schoolFeesAmount: 18500,
      rationEmergencyAmount: 4000,
    },
    zakat: {
      assessableCashSavings: 770,
      assessableGoldSilverValue: 0,
      assessableInvestmentsTradeGoods: 0,
      deductibleImmediateLiabilities: 21500,
      deductibleBasicMonthlyLivingExpenses: 11500,
      netAssessableWealth: 0,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: true,
      recipientCategory: 'faqir',
      preliminaryEligibility: 'Eligible',
      scholarlyNotes: 'Beneficiary has zero assessable gold/savings and substantial essential liabilities; prime Zakat recipient.',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: false,
      costEstimateVerified: true,
      doctorHospitalVerified: false,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Home visit conducted by Br. Tariq on 24 Sept. Confirmed tailoring status and rent receipts.',
      inconsistencyFlags: [],
    },
    decisionHistory: [],
  }),

  // 2. Mohammed Irfan - Daily wage mason with severe spinal trauma disability from fall (PWD)
  createSampleCase({
    id: 'IAN-2026-1002',
    beneficiaryCode: 'BEN-1002',
    fullName: 'Mohammed Irfan',
    dateOfBirth: '1984-11-20',
    calculatedAge: 41,
    gender: 'Male',
    phone: '+91 97410 88219',
    address: 'Slum Quarters, Behind Bamboo Bazaar, Shivajinagar',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560051',
    caseType: 'disability',
    title: 'Mason with paraplegia following construction fall; requires wheelchair & home mobility aids',
    narrativeDescription:
      'Irfan suffered a T12 spinal cord injury after falling from scaffolding 6 months ago. He has complete lower-limb paraplegia and bladder catheterization. Formerly sole breadwinner for wife and 2 children. Zero income currently. Family survives on neighbour charity. Needs specialized active wheelchair and catheter supplies.',
    requestedAmount: 45000,
    minimumEffectiveAmount: 28000,
    verifiedRequirement: 45000,
    fundEligibility: ['Zakat', 'General Welfare', 'Medical'],
    status: 'Ready for Decision',
    isDemoCase: true,
    createdAt: '2026-09-22T11:00:00Z',
    updatedAt: '2026-10-03T09:40:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Mohammed Irfan',
        relationship: 'Self',
        age: 41,
        gender: 'Male',
        employmentStatus: 'Unable to Work',
        monthlyIncome: 0,
        hasDisability: true,
        disabilityDetails: 'Paraplegia secondary to spinal trauma',
        isDependent: true,
      },
      {
        id: 'hh-2',
        name: 'Rubeena Begum',
        relationship: 'Spouse',
        age: 36,
        gender: 'Female',
        employmentStatus: 'Unable to Work',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
        chronicCareNeeds: true,
      },
      {
        id: 'hh-3',
        name: 'Suhail',
        relationship: 'Son',
        age: 9,
        gender: 'Male',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
      {
        id: 'hh-4',
        name: 'Saba',
        relationship: 'Daughter',
        age: 5,
        gender: 'Female',
        employmentStatus: 'Child',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
    ],
    financial: {
      dependableMonthlyIncome: 0,
      irregularMonthlyIncome: 1200,
      totalHouseholdIncome: 1200,
      perCapitaIncome: 300,
      incomeStability: 'no_reliable_income',
      incomeSources: [],
      essentialMonthlyExpenses: {
        food: 4000,
        rent: 2800,
        utilities: 600,
        essentialMedicines: 2400, // catheters, dressing, urinary antiseptic
        essentialTransport: 400,
        education: 500,
        caregiving: 0,
        otherEssential: 300,
        total: 11000,
      },
      liquidAssets: {
        cash: 180,
        bankBalance: 240,
        savings: 0,
        goldSilverValue: 0,
        investments: 0,
        totalLiquid: 420,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 0,
        livestockValue: 0,
        businessAssets: 0,
        totalPhysical: 0,
      },
      debtObligations: {
        totalOutstanding: 45000,
        monthlyDebtPayment: 500,
        debtType: 'Medical treatment debt taken for emergency spinal surgery',
        rentArrears: 5600,
        medicalDebt: 32000,
        utilityArrears: 800,
        foodDebt: 6600,
        essentialEducationDebt: 0,
        consequenceOfNonPayment: 'Local lender demanding interest; landlord threatening eviction',
      },
      coverageRatio: 0.0,
      reserveMonths: 0.04,
      debtBurdenRatio: 0.42,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: true,
        disabilityType: 'Locomotor Disability / Paraplegia',
        percentage: 85,
        udidNumber: 'KA142026008129',
        functionalImpact: 'severe',
        requiresCaregiver: true,
        caregiverImpact: 'Wife full-time occupied assisting transfers and catheter care',
        additionalDisabilityExpenses: 2400,
      },
      dependencyBurden: {
        totalMembers: 4,
        totalEarners: 0,
        totalDependents: 4,
        childrenCount: 2,
        elderlyCount: 0,
        disabledDependentsCount: 1,
        dependencyRatio: 4.0,
      },
      familyStructure: {
        circumstance: 'single_caregiver',
        category: 'intact_family',
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 41,
        lifeStage: 'adult',
        createsVulnerability: false,
      },
      chronicCareSafeguarding: {
        hasChronicIllness: true,
        chronicIllnessDetails: 'Neurogenic bladder, bed sore risk',
        recurringMedicationNeeds: true,
        monthlyMedicationCost: 2400,
        safeguardingRisk: 'moderate',
        abuseNeglectRisk: false,
        unsafeLivingEnvironment: true,
      },
    },
    deprivation: {
      foodSecurity: {
        score: 3,
        mealsPerDay: 2,
        skippedMeals: true,
        daysFoodRemaining: 2,
        childrenAffected: true,
      },
      housingCondition: {
        score: 2,
        type: 'rented_arrears_eviction',
        rentArrearsMonths: 2,
        evictionNoticeReceived: true,
        overcrowded: true,
        weatherExposure: false,
      },
      utilitiesAccess: {
        score: 1,
        electricityAvailable: true,
        cleanWaterAvailable: true,
        cleanCookingFuelAvailable: false,
        adequateSanitationAvailable: false, // shared outdoor Indian latrine inaccessible by wheelchair
      },
      healthAccess: {
        score: 2,
        medicationUnavailable: true,
        treatmentInterruptedDueToCost: true,
        inabilityToAffordEssentialCare: true,
      },
      educationDeprivation: {
        score: 1,
        childrenOutOfSchool: false,
        dropoutRiskDueToFees: true,
        feeArrearsPresent: true,
        examAdmissionBarrier: false,
      },
      otherBasicNeeds: {
        score: 2,
        inadequateClothing: true,
        inadequateHygieneSanitaryAccess: true,
        lackEssentialTransport: true,
        lackCommunicationDevice: false,
      },
    },
    severity: {
      timeUrgency: {
        timeUntilHarm: '1_to_2_weeks',
        points: 6,
      },
      consequenceOfNoAssistance: {
        consequence: 'severe_irreversible_harm',
        points: 6,
      },
      essentialityOfIntervention: {
        level: 'critical',
        points: 4,
      },
      expectedBenefit: {
        level: 'restores_functioning_or_life_saving',
        points: 6,
        clinicianInformedNote: 'Wheelchair enables mobility outside the room; hygiene supplies prevent urosepsis.',
      },
      emergencyTrigger: false,
    },
    supportGap: {
      familyCommunitySupport: {
        level: 'minimal_sympathetic',
        points: 2,
        notes: 'Co-workers raised ₹8,000 immediately after accident; no ongoing support.',
      },
      governmentOtherSchemes: {
        level: 'applied_pending',
        points: 2,
        schemesChecked: ['Karnataka Disability Pension ₹1400/mo (Applied, under process)'],
      },
      remainingFundingGap: {
        verifiedTotalNeed: 45000,
        existingAvailableFunds: 0,
        otherCommittedFunds: 0,
        requestedFromIlAnNoor: 45000,
        minimumEffectiveAmount: 28000,
        gapRatio: 1.0,
        points: 4,
      },
    },
    caseSpecificData: {
      deviceRequired: 'Rigid-frame manual folding wheelchair with roho cushion & urine bag accessories',
      doctorRecommendationAvailable: true,
    },
    zakat: {
      assessableCashSavings: 420,
      assessableGoldSilverValue: 0,
      assessableInvestmentsTradeGoods: 0,
      deductibleImmediateLiabilities: 45000,
      deductibleBasicMonthlyLivingExpenses: 11000,
      netAssessableWealth: 0,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: true,
      recipientCategory: 'faqir',
      preliminaryEligibility: 'Eligible',
      scholarlyNotes: 'Clear Zakat recipient under Fuqara and Gharimin categories.',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: true,
      costEstimateVerified: true,
      doctorHospitalVerified: true,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Hospital discharge summary from Victoria Hospital verified. UDID verified online.',
      inconsistencyFlags: [],
    },
    decisionHistory: [],
  }),

  // 3. Ayesha Siddiqa - 48yo Breast Cancer Patient (Clinical Assessment, Curative Stage II)
  createSampleCase({
    id: 'IAN-2026-1003',
    beneficiaryCode: 'BEN-1003',
    fullName: 'Ayesha Siddiqa',
    dateOfBirth: '1978-06-15',
    calculatedAge: 48,
    gender: 'Female',
    phone: '+91 94480 34110',
    address: 'Old Police Station Road, Channapatna',
    city: 'Ramanagara',
    district: 'Ramanagara',
    state: 'Karnataka',
    pincode: '562160',
    caseType: 'medical',
    title: 'Stage IIB Infiltrating Ductal Carcinoma Breast; urgent Chemotherapy Cycle 3 & 4 funding',
    narrativeDescription:
      '48-year-old woman diagnosed with Stage IIB Breast Cancer. Modified Radical Mastectomy performed at Kidwai Memorial Institute of Oncology. Requires 6 cycles of Adjuvant Chemotherapy (AC-T regimen). Family funded first 2 cycles by pledging small ancestral silver. Cannot fund cycles 3 & 4. Treating oncologist confirms treatment is curative in intent with high 5-year survival probability if completed without interruption.',
    requestedAmount: 60000,
    minimumEffectiveAmount: 35000,
    verifiedRequirement: 60000,
    fundEligibility: ['Zakat', 'Medical', 'General Welfare'],
    status: 'Emergency Review',
    isDemoCase: true,
    createdAt: '2026-09-25T15:00:00Z',
    updatedAt: '2026-10-04T12:00:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Ayesha Siddiqa',
        relationship: 'Self',
        age: 48,
        gender: 'Female',
        employmentStatus: 'Unable to Work',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
        chronicCareNeeds: true,
      },
      {
        id: 'hh-2',
        name: 'Bashir Ahmed',
        relationship: 'Spouse',
        age: 54,
        gender: 'Male',
        employmentStatus: 'Daily Wage',
        monthlyIncome: 7000,
        hasDisability: false,
        isDependent: false,
      },
      {
        id: 'hh-3',
        name: 'Farhan Ahmed',
        relationship: 'Son',
        age: 19,
        gender: 'Male',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
    ],
    financial: {
      dependableMonthlyIncome: 7000,
      irregularMonthlyIncome: 1000,
      totalHouseholdIncome: 8000,
      perCapitaIncome: 2666,
      incomeStability: 'highly_unstable',
      incomeSources: [
        { id: 'inc-1', source: 'Silk loom daily wages', amount: 7000, earnerName: 'Bashir Ahmed', isRegular: false },
      ],
      essentialMonthlyExpenses: {
        food: 4500,
        rent: 2500,
        utilities: 700,
        essentialMedicines: 1200,
        essentialTransport: 1500, // Bangalore-Channapatna hospital visits
        education: 0,
        caregiving: 0,
        otherEssential: 400,
        total: 10800,
      },
      liquidAssets: {
        cash: 600,
        bankBalance: 1200,
        savings: 0,
        goldSilverValue: 0,
        investments: 0,
        totalLiquid: 1800,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 0,
        livestockValue: 0,
        businessAssets: 0,
        totalPhysical: 0,
      },
      debtObligations: {
        totalOutstanding: 65000,
        monthlyDebtPayment: 1500,
        debtType: 'Hospitalization and surgery debt',
        rentArrears: 2500,
        medicalDebt: 55000,
        utilityArrears: 0,
        foodDebt: 7500,
        essentialEducationDebt: 0,
        consequenceOfNonPayment: 'Local lenders refusing further emergency loans',
      },
      coverageRatio: 0.65,
      reserveMonths: 0.17,
      debtBurdenRatio: 0.21,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: false,
        functionalImpact: 'moderate',
        requiresCaregiver: true,
        caregiverImpact: 'Husband misses wage labor 2-3 days per week to accompany to oncology day-care',
        additionalDisabilityExpenses: 1500,
      },
      dependencyBurden: {
        totalMembers: 3,
        totalEarners: 1,
        totalDependents: 2,
        childrenCount: 0,
        elderlyCount: 0,
        disabledDependentsCount: 0,
        dependencyRatio: 2.0,
      },
      familyStructure: {
        circumstance: 'some_limitation',
        category: 'intact_family',
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 48,
        lifeStage: 'adult',
        createsVulnerability: false,
        ageVulnerabilityNote: 'Age 48 evaluated in medical context; excellent physiological resilience for completion of chemotherapy.',
      },
      chronicCareSafeguarding: {
        hasChronicIllness: true,
        chronicIllnessDetails: 'Stage IIB Breast Cancer under active chemotherapy',
        recurringMedicationNeeds: true,
        monthlyMedicationCost: 8000,
        safeguardingRisk: 'none',
        abuseNeglectRisk: false,
        unsafeLivingEnvironment: false,
      },
    },
    deprivation: {
      foodSecurity: {
        score: 2,
        mealsPerDay: 2,
        skippedMeals: false,
        daysFoodRemaining: 5,
        childrenAffected: false,
      },
      housingCondition: {
        score: 1,
        type: 'rented_stable',
        rentArrearsMonths: 1,
        evictionNoticeReceived: false,
        overcrowded: false,
        weatherExposure: false,
      },
      utilitiesAccess: {
        score: 0,
        electricityAvailable: true,
        cleanWaterAvailable: true,
        cleanCookingFuelAvailable: true,
        adequateSanitationAvailable: true,
      },
      healthAccess: {
        score: 2,
        medicationUnavailable: true,
        treatmentInterruptedDueToCost: true,
        inabilityToAffordEssentialCare: true,
      },
      educationDeprivation: {
        score: 0,
        childrenOutOfSchool: false,
        dropoutRiskDueToFees: false,
        feeArrearsPresent: false,
        examAdmissionBarrier: false,
      },
      otherBasicNeeds: {
        score: 1,
        inadequateClothing: false,
        inadequateHygieneSanitaryAccess: false,
        lackEssentialTransport: true,
        lackCommunicationDevice: false,
      },
    },
    severity: {
      timeUrgency: {
        timeUntilHarm: 'less_than_72h',
        points: 8,
      },
      consequenceOfNoAssistance: {
        consequence: 'severe_irreversible_harm',
        points: 6,
      },
      essentialityOfIntervention: {
        level: 'critical',
        points: 4,
      },
      expectedBenefit: {
        level: 'restores_functioning_or_life_saving',
        points: 6,
        clinicianInformedNote:
          'Oncologist confirms curative intent: completing 4 cycles gives ~80% disease-free 5-year survival. Interruption risks recurrence and chemo-resistance.',
      },
      emergencyTrigger: true,
      emergencyReason: 'Chemotherapy cycle 3 scheduled for Thursday at Kidwai Oncology; missing deadline causes protocol failure.',
    },
    supportGap: {
      familyCommunitySupport: {
        level: 'minimal_sympathetic',
        points: 2,
      },
      governmentOtherSchemes: {
        level: 'partial_scheme_accessible',
        points: 1,
        schemesChecked: ['Ayushman Bharat PM-JAY / Arogya Karnataka (Covers hospital bed; chemo drugs currently out of stock in pharmacy)'],
      },
      remainingFundingGap: {
        verifiedTotalNeed: 60000,
        existingAvailableFunds: 0,
        otherCommittedFunds: 10000,
        requestedFromIlAnNoor: 50000,
        minimumEffectiveAmount: 35000,
        gapRatio: 0.83,
        points: 4,
      },
    },
    caseSpecificData: {
      diagnosis: 'Infiltrating Ductal Carcinoma Breast, Left',
      stage: 'Stage IIB (T2 N1 M0)',
      treatmentIntent: 'Curative adjuvant chemotherapy',
      hospital: 'Kidwai Memorial Institute of Oncology, Bangalore',
      treatingDoctor: 'Dr. Ramesh Kumar, Medical Oncology',
      estimateSlipVerified: true,
    },
    zakat: {
      assessableCashSavings: 1800,
      assessableGoldSilverValue: 0,
      assessableInvestmentsTradeGoods: 0,
      deductibleImmediateLiabilities: 65000,
      deductibleBasicMonthlyLivingExpenses: 10800,
      netAssessableWealth: 0,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: true,
      recipientCategory: 'gharimin',
      preliminaryEligibility: 'Eligible',
      scholarlyNotes: 'Severe medical debt and zero assets; fully eligible under medical Zakat guidelines.',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: true,
      costEstimateVerified: true,
      doctorHospitalVerified: true,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Hospital inpatient ID, biopsy report, and doctor chemo prescription authenticated.',
      inconsistencyFlags: [],
    },
    decisionHistory: [],
  }),

  // 4. Zaid Khan - 12yo Orphan child with disabled grandmother
  createSampleCase({
    id: 'IAN-2026-1004',
    beneficiaryCode: 'BEN-1004',
    fullName: 'Zaid Khan',
    dateOfBirth: '2014-08-05',
    calculatedAge: 12,
    gender: 'Male',
    phone: '+91 99801 11452',
    address: 'Near Bilal Masjid, Neelasandra',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560047',
    caseType: 'orphan',
    title: '12-year-old double orphan supported by 72yo frail grandmother facing eviction and school dropout',
    narrativeDescription:
      'Both of Zaid’s parents died in a road accident four years ago. He is cared for by his 72-year-old maternal grandmother who suffers from severe osteoarthritis and cataract. They survive on elderly pension (₹1,200) and small neighborhood charity. School fee arrears have mounted to ₹16,000, and school has issued a formal transfer certificate threat.',
    requestedAmount: 32000,
    minimumEffectiveAmount: 20000,
    verifiedRequirement: 32000,
    fundEligibility: ['Zakat', 'Education', 'General Welfare'],
    status: 'Ready for Decision',
    isDemoCase: true,
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-10-01T16:00:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Zaid Khan',
        relationship: 'Primary Beneficiary',
        age: 12,
        gender: 'Male',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
        educationStatus: 'Class 6',
      },
      {
        id: 'hh-2',
        name: 'Khurshida Begum',
        relationship: 'Maternal Grandmother',
        age: 72,
        gender: 'Female',
        employmentStatus: 'Retired',
        monthlyIncome: 1200,
        hasDisability: true,
        disabilityDetails: 'Severe degenerative joint disease',
        isDependent: false,
        chronicCareNeeds: true,
      },
    ],
    financial: {
      dependableMonthlyIncome: 1200,
      irregularMonthlyIncome: 800,
      totalHouseholdIncome: 2000,
      perCapitaIncome: 1000,
      incomeStability: 'mostly_stable', // pension
      incomeSources: [
        { id: 'inc-1', source: 'Old Age Pension (Sandhya Suraksha)', amount: 1200, earnerName: 'Khurshida Begum', isRegular: true },
      ],
      essentialMonthlyExpenses: {
        food: 2600,
        rent: 2000,
        utilities: 400,
        essentialMedicines: 600,
        essentialTransport: 200,
        education: 1400,
        caregiving: 0,
        otherEssential: 300,
        total: 7500,
      },
      liquidAssets: {
        cash: 250,
        bankBalance: 400,
        savings: 0,
        goldSilverValue: 0,
        investments: 0,
        totalLiquid: 650,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 0,
        livestockValue: 0,
        businessAssets: 0,
        totalPhysical: 0,
      },
      debtObligations: {
        totalOutstanding: 19500,
        monthlyDebtPayment: 0,
        debtType: 'Rent arrears and school fees',
        rentArrears: 4000,
        medicalDebt: 0,
        utilityArrears: 500,
        foodDebt: 2000,
        essentialEducationDebt: 13000,
        consequenceOfNonPayment: 'Child facing expulsion; landlord threatening removal',
      },
      coverageRatio: 0.16,
      reserveMonths: 0.08,
      debtBurdenRatio: 0.0,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: true,
        functionalImpact: 'moderate',
        requiresCaregiver: true,
        caregiverImpact: 'Grandmother physically frail; child assists with household water collection',
        additionalDisabilityExpenses: 600,
      },
      dependencyBurden: {
        totalMembers: 2,
        totalEarners: 0,
        totalDependents: 2,
        childrenCount: 1,
        elderlyCount: 1,
        disabledDependentsCount: 1,
        dependencyRatio: 2.0,
      },
      familyStructure: {
        circumstance: 'no_reliable_guardian',
        category: 'orphan',
        orphanDetails: {
          parentsAlive: 'none',
          guardianAvailable: true,
          guardianRelationship: 'Grandmother (frail, elderly)',
          guardianCapacity: 'severely_deprived',
        },
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 12,
        lifeStage: 'child',
        createsVulnerability: true,
        ageVulnerabilityNote: 'Minor orphan dependent on elderly grandmother with no adult working breadwinner.',
      },
      chronicCareSafeguarding: {
        hasChronicIllness: true,
        chronicIllnessDetails: 'Grandmother arthritis & hypertension',
        recurringMedicationNeeds: true,
        monthlyMedicationCost: 600,
        safeguardingRisk: 'moderate',
        abuseNeglectRisk: false,
        unsafeLivingEnvironment: false,
      },
    },
    deprivation: {
      foodSecurity: {
        score: 3,
        mealsPerDay: 2,
        skippedMeals: true,
        daysFoodRemaining: 3,
        childrenAffected: true,
      },
      housingCondition: {
        score: 2,
        type: 'rented_arrears_eviction',
        rentArrearsMonths: 2,
        evictionNoticeReceived: true,
        overcrowded: false,
        weatherExposure: false,
      },
      utilitiesAccess: {
        score: 1,
        electricityAvailable: true,
        cleanWaterAvailable: true,
        cleanCookingFuelAvailable: false,
        adequateSanitationAvailable: true,
      },
      healthAccess: {
        score: 1,
        medicationUnavailable: true,
        treatmentInterruptedDueToCost: false,
        inabilityToAffordEssentialCare: true,
      },
      educationDeprivation: {
        score: 2,
        childrenOutOfSchool: false,
        dropoutRiskDueToFees: true,
        feeArrearsPresent: true,
        examAdmissionBarrier: true,
      },
      otherBasicNeeds: {
        score: 1,
        inadequateClothing: true,
        inadequateHygieneSanitaryAccess: false,
        lackEssentialTransport: false,
        lackCommunicationDevice: false,
      },
    },
    severity: {
      timeUrgency: {
        timeUntilHarm: '1_to_2_weeks',
        points: 6,
      },
      consequenceOfNoAssistance: {
        consequence: 'serious_hardship',
        points: 4,
      },
      essentialityOfIntervention: {
        level: 'essential',
        points: 3,
      },
      expectedBenefit: {
        level: 'major_stabilization',
        points: 5,
        clinicianInformedNote: 'School tuition fee payment and ration support preserves educational continuity and nutrition.',
      },
      emergencyTrigger: false,
    },
    supportGap: {
      familyCommunitySupport: {
        level: 'minimal_sympathetic',
        points: 2,
        notes: 'Mosque committee provides occasional food parcels during Ramadan only.',
      },
      governmentOtherSchemes: {
        level: 'partial_scheme_accessible',
        points: 1,
        schemesChecked: ['Old age pension received; National Orphan scholarship not yet processed.'],
      },
      remainingFundingGap: {
        verifiedTotalNeed: 32000,
        existingAvailableFunds: 0,
        otherCommittedFunds: 4000,
        requestedFromIlAnNoor: 28000,
        minimumEffectiveAmount: 20000,
        gapRatio: 0.88,
        points: 4,
      },
    },
    caseSpecificData: {
      schoolName: 'Al-Huda High School, Neelasandra',
      annualFees: 16000,
      rationSupportRequired: 6000,
    },
    zakat: {
      assessableCashSavings: 650,
      assessableGoldSilverValue: 0,
      assessableInvestmentsTradeGoods: 0,
      deductibleImmediateLiabilities: 19500,
      deductibleBasicMonthlyLivingExpenses: 7500,
      netAssessableWealth: 0,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: true,
      recipientCategory: 'faqir',
      preliminaryEligibility: 'Eligible',
      scholarlyNotes: 'Double orphan under impoverished care; classic eligible recipient.',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: false,
      costEstimateVerified: true,
      doctorHospitalVerified: false,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Death certificates of father & mother inspected. School fee ledger verified.',
      inconsistencyFlags: [],
    },
    decisionHistory: [],
  }),

  // 5. Abdul Rahman - 76yo elderly man living alone in dilapidated room (Elderly Support)
  createSampleCase({
    id: 'IAN-2026-1005',
    beneficiaryCode: 'BEN-1005',
    fullName: 'Abdul Rahman',
    dateOfBirth: '1950-01-10',
    calculatedAge: 76,
    gender: 'Male',
    phone: '+91 93412 90182',
    address: 'Old Tin Shed, Near Goripalya Bridge',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560018',
    caseType: 'elderly',
    title: '76-year-old destitute senior living alone; no living kin, acute arthritis and nutrition deficit',
    narrativeDescription:
      'Abdul Rahman is 76 years old, a former cycle repair mechanic whose wife passed away 12 years ago. They had no children. He lives alone in a single rented tin room. Severe osteoarthritis has left him unable to walk without support. Neighbors give him leftover cooked food once a day. Landlord has threatened eviction due to unpaid rent.',
    requestedAmount: 24000,
    minimumEffectiveAmount: 15000,
    verifiedRequirement: 24000,
    fundEligibility: ['Zakat', 'General Welfare'],
    status: 'Ready for Decision',
    isDemoCase: true,
    createdAt: '2026-09-28T14:20:00Z',
    updatedAt: '2026-10-04T10:00:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Abdul Rahman',
        relationship: 'Self',
        age: 76,
        gender: 'Male',
        employmentStatus: 'Unable to Work',
        monthlyIncome: 0,
        hasDisability: true,
        disabilityDetails: 'Severe mobility limitation / Osteoarthritis',
        isDependent: true,
      },
    ],
    financial: {
      dependableMonthlyIncome: 0,
      irregularMonthlyIncome: 500,
      totalHouseholdIncome: 500,
      perCapitaIncome: 500,
      incomeStability: 'no_reliable_income',
      incomeSources: [],
      essentialMonthlyExpenses: {
        food: 2000,
        rent: 1800,
        utilities: 300,
        essentialMedicines: 800,
        essentialTransport: 100,
        education: 0,
        caregiving: 0,
        otherEssential: 200,
        total: 5200,
      },
      liquidAssets: {
        cash: 120,
        bankBalance: 80,
        savings: 0,
        goldSilverValue: 0,
        investments: 0,
        totalLiquid: 200,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 0,
        livestockValue: 0,
        businessAssets: 0,
        totalPhysical: 0,
      },
      debtObligations: {
        totalOutstanding: 7500,
        monthlyDebtPayment: 0,
        debtType: 'Rent arrears',
        rentArrears: 5400,
        medicalDebt: 1200,
        utilityArrears: 400,
        foodDebt: 500,
        essentialEducationDebt: 0,
        consequenceOfNonPayment: 'Eviction into street within 10 days',
      },
      coverageRatio: 0.0,
      reserveMonths: 0.03,
      debtBurdenRatio: 0.0,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: true,
        functionalImpact: 'severe',
        requiresCaregiver: true,
        caregiverImpact: 'Dependent on neighbor volunteers for fetching drinking water and bathing',
        additionalDisabilityExpenses: 800,
      },
      dependencyBurden: {
        totalMembers: 1,
        totalEarners: 0,
        totalDependents: 1,
        childrenCount: 0,
        elderlyCount: 1,
        disabledDependentsCount: 1,
        dependencyRatio: 1.0,
      },
      familyStructure: {
        circumstance: 'no_reliable_guardian',
        category: 'elderly_alone',
        elderlyDetails: {
          livesAlone: true,
          hasCaregiver: false,
          functionalIndependence: 'dependent',
        },
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 76,
        lifeStage: 'older_adult',
        createsVulnerability: true,
        ageVulnerabilityNote: 'Advanced age combined with complete absence of kin and functional dependency.',
      },
      chronicCareSafeguarding: {
        hasChronicIllness: true,
        chronicIllnessDetails: 'Osteoarthritis, benign prostatic hyperplasia, cataracts',
        recurringMedicationNeeds: true,
        monthlyMedicationCost: 800,
        safeguardingRisk: 'high',
        abuseNeglectRisk: true,
        unsafeLivingEnvironment: true,
      },
    },
    deprivation: {
      foodSecurity: {
        score: 3,
        mealsPerDay: 1,
        skippedMeals: true,
        daysFoodRemaining: 1,
        childrenAffected: false,
      },
      housingCondition: {
        score: 3,
        type: 'unsafe_structure',
        rentArrearsMonths: 3,
        evictionNoticeReceived: true,
        overcrowded: false,
        weatherExposure: true,
      },
      utilitiesAccess: {
        score: 2,
        electricityAvailable: false, // disconnected for non-payment
        cleanWaterAvailable: false,
        cleanCookingFuelAvailable: false,
        adequateSanitationAvailable: false,
      },
      healthAccess: {
        score: 2,
        medicationUnavailable: true,
        treatmentInterruptedDueToCost: true,
        inabilityToAffordEssentialCare: true,
      },
      educationDeprivation: {
        score: 0,
        childrenOutOfSchool: false,
        dropoutRiskDueToFees: false,
        feeArrearsPresent: false,
        examAdmissionBarrier: false,
      },
      otherBasicNeeds: {
        score: 2,
        inadequateClothing: true,
        inadequateHygieneSanitaryAccess: true,
        lackEssentialTransport: true,
        lackCommunicationDevice: true,
      },
    },
    severity: {
      timeUrgency: {
        timeUntilHarm: '1_to_2_weeks',
        points: 6,
      },
      consequenceOfNoAssistance: {
        consequence: 'threat_to_life_or_shelter',
        points: 7,
      },
      essentialityOfIntervention: {
        level: 'critical',
        points: 4,
      },
      expectedBenefit: {
        level: 'meaningful_relief',
        points: 4,
      },
      emergencyTrigger: false,
    },
    supportGap: {
      familyCommunitySupport: {
        level: 'no_support',
        points: 3,
      },
      governmentOtherSchemes: {
        level: 'none_available_or_rejected',
        points: 3,
        schemesChecked: ['Old age pension application rejected due to mismatch in name spelling on Aadhaar'],
      },
      remainingFundingGap: {
        verifiedTotalNeed: 24000,
        existingAvailableFunds: 0,
        otherCommittedFunds: 0,
        requestedFromIlAnNoor: 24000,
        minimumEffectiveAmount: 15000,
        gapRatio: 1.0,
        points: 4,
      },
    },
    caseSpecificData: {
      rentArrears: 5400,
      rationKits6Months: 12000,
      medicalAssistance: 6600,
    },
    zakat: {
      assessableCashSavings: 200,
      assessableGoldSilverValue: 0,
      assessableInvestmentsTradeGoods: 0,
      deductibleImmediateLiabilities: 7500,
      deductibleBasicMonthlyLivingExpenses: 5200,
      netAssessableWealth: 0,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: true,
      recipientCategory: 'faqir',
      preliminaryEligibility: 'Eligible',
      scholarlyNotes: 'Isolated destitute elderly without kin; exemplary recipient for ongoing basic living support.',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: true,
      costEstimateVerified: true,
      doctorHospitalVerified: false,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Investigator Br. Salman visited tin shed. Confirmed living conditions and lack of kin.',
      inconsistencyFlags: [],
    },
    decisionHistory: [],
  }),

  // 6. Imran Ahmed - Livelihood Restart (Tea stall destroyed in road widening/fire)
  createSampleCase({
    id: 'IAN-2026-1006',
    beneficiaryCode: 'BEN-1006',
    fullName: 'Imran Ahmed',
    dateOfBirth: '1987-03-22',
    calculatedAge: 39,
    gender: 'Male',
    phone: '+91 98860 77123',
    address: 'Near Old Bus Stand, Hoskote',
    city: 'Hoskote',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    pincode: '562114',
    caseType: 'livelihood',
    title: 'Tea stall vendor whose pushcart and stove were destroyed; livelihood restoration grant request',
    narrativeDescription:
      'Imran operated a roadside tea and snack stall supporting his family of five (wife, elderly mother, two children). An accidental short-circuit and fire in adjacent shops completely gutted his pushcart, stove, and utensils. Prior to the fire he earned ₹18,000/month consistently. Now working as temporary helper earning ₹250/day irregularly. Requires ₹32,000 to construct a new cart and purchase commercial gas stove and utensils.',
    requestedAmount: 32000,
    minimumEffectiveAmount: 22000,
    verifiedRequirement: 32000,
    fundEligibility: ['Zakat', 'General Welfare'],
    status: 'Ready for Decision',
    isDemoCase: true,
    createdAt: '2026-09-29T10:10:00Z',
    updatedAt: '2026-10-02T11:30:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Imran Ahmed',
        relationship: 'Self',
        age: 39,
        gender: 'Male',
        employmentStatus: 'Daily Wage',
        monthlyIncome: 5500,
        hasDisability: false,
        isDependent: false,
      },
      {
        id: 'hh-2',
        name: 'Shabana Parveen',
        relationship: 'Spouse',
        age: 34,
        gender: 'Female',
        employmentStatus: 'Unemployed',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
      {
        id: 'hh-3',
        name: 'Noor Jahan',
        relationship: 'Mother',
        age: 68,
        gender: 'Female',
        employmentStatus: 'Retired',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
      {
        id: 'hh-4',
        name: 'Rayan',
        relationship: 'Son',
        age: 8,
        gender: 'Male',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
      {
        id: 'hh-5',
        name: 'Abrar',
        relationship: 'Son',
        age: 5,
        gender: 'Male',
        employmentStatus: 'Student',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
    ],
    financial: {
      dependableMonthlyIncome: 5500,
      irregularMonthlyIncome: 1500,
      totalHouseholdIncome: 7000,
      perCapitaIncome: 1400,
      incomeStability: 'variable',
      incomeSources: [
        { id: 'inc-1', source: 'Temporary loading helper', amount: 5500, earnerName: 'Imran Ahmed', isRegular: false },
      ],
      essentialMonthlyExpenses: {
        food: 5500,
        rent: 3200,
        utilities: 700,
        essentialMedicines: 800,
        essentialTransport: 400,
        education: 1200,
        caregiving: 0,
        otherEssential: 400,
        total: 12200,
      },
      liquidAssets: {
        cash: 950,
        bankBalance: 1100,
        savings: 0,
        goldSilverValue: 0,
        investments: 0,
        totalLiquid: 2050,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 0,
        livestockValue: 0,
        businessAssets: 0,
        totalPhysical: 0,
      },
      debtObligations: {
        totalOutstanding: 14000,
        monthlyDebtPayment: 1000,
        debtType: 'Rent arrears and ration shop',
        rentArrears: 6400,
        medicalDebt: 0,
        utilityArrears: 600,
        foodDebt: 7000,
        essentialEducationDebt: 0,
        consequenceOfNonPayment: 'Mounting debts and risk of school fee default',
      },
      coverageRatio: 0.45,
      reserveMonths: 0.16,
      debtBurdenRatio: 0.18,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: false,
        functionalImpact: 'none',
        requiresCaregiver: false,
        additionalDisabilityExpenses: 0,
      },
      dependencyBurden: {
        totalMembers: 5,
        totalEarners: 1,
        totalDependents: 4,
        childrenCount: 2,
        elderlyCount: 1,
        disabledDependentsCount: 0,
        dependencyRatio: 4.0,
      },
      familyStructure: {
        circumstance: 'some_limitation',
        category: 'intact_family',
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 39,
        lifeStage: 'adult',
        createsVulnerability: false,
      },
      chronicCareSafeguarding: {
        hasChronicIllness: false,
        recurringMedicationNeeds: true,
        monthlyMedicationCost: 800, // mother diabetic pills
        safeguardingRisk: 'none',
        abuseNeglectRisk: false,
        unsafeLivingEnvironment: false,
      },
    },
    deprivation: {
      foodSecurity: {
        score: 2,
        mealsPerDay: 2,
        skippedMeals: false,
        daysFoodRemaining: 4,
        childrenAffected: false,
      },
      housingCondition: {
        score: 1,
        type: 'rented_arrears_eviction',
        rentArrearsMonths: 2,
        evictionNoticeReceived: false,
        overcrowded: true,
        weatherExposure: false,
      },
      utilitiesAccess: {
        score: 0,
        electricityAvailable: true,
        cleanWaterAvailable: true,
        cleanCookingFuelAvailable: true,
        adequateSanitationAvailable: true,
      },
      healthAccess: {
        score: 1,
        medicationUnavailable: false,
        treatmentInterruptedDueToCost: false,
        inabilityToAffordEssentialCare: true,
      },
      educationDeprivation: {
        score: 1,
        childrenOutOfSchool: false,
        dropoutRiskDueToFees: true,
        feeArrearsPresent: true,
        examAdmissionBarrier: false,
      },
      otherBasicNeeds: {
        score: 0,
        inadequateClothing: false,
        inadequateHygieneSanitaryAccess: false,
        lackEssentialTransport: false,
        lackCommunicationDevice: false,
      },
    },
    severity: {
      timeUrgency: {
        timeUntilHarm: '2_to_4_weeks',
        points: 4,
      },
      consequenceOfNoAssistance: {
        consequence: 'serious_hardship',
        points: 4,
      },
      essentialityOfIntervention: {
        level: 'essential',
        points: 3,
      },
      expectedBenefit: {
        level: 'major_stabilization',
        points: 5,
        clinicianInformedNote: 'Vendor was self-reliant for 7 years prior to accident. High feasibility of restoring full self-sufficiency.',
      },
      emergencyTrigger: false,
    },
    supportGap: {
      familyCommunitySupport: {
        level: 'moderate_occasional',
        points: 1,
        notes: 'Relatives lent ₹3,000 for emergency family rations.',
      },
      governmentOtherSchemes: {
        level: 'none_available_or_rejected',
        points: 3,
        schemesChecked: ['Street vendor PM-SVANidhi scheme inaccessible due to past CIBIL check'],
      },
      remainingFundingGap: {
        verifiedTotalNeed: 32000,
        existingAvailableFunds: 0,
        otherCommittedFunds: 5000,
        requestedFromIlAnNoor: 27000,
        minimumEffectiveAmount: 22000,
        gapRatio: 0.84,
        points: 4,
      },
    },
    caseSpecificData: {
      cartQuotation: 18000,
      stoveAndCylinder: 8000,
      initialProvisions: 6000,
      projectedIncome: 16000,
    },
    zakat: {
      assessableCashSavings: 2050,
      assessableGoldSilverValue: 0,
      assessableInvestmentsTradeGoods: 0,
      deductibleImmediateLiabilities: 14000,
      deductibleBasicMonthlyLivingExpenses: 12200,
      netAssessableWealth: 0,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: true,
      recipientCategory: 'miskeen',
      preliminaryEligibility: 'Eligible',
      scholarlyNotes: 'Livelihood capital for a needy Muslim earner to exit poverty is highly recommended under Zakat principles (Tamlik).',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: false,
      costEstimateVerified: true,
      doctorHospitalVerified: false,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Fire accident reported to local station; carpenter quotation for pushcart authenticated.',
      inconsistencyFlags: [],
    },
    decisionHistory: [],
  }),

  // 7. Bilal Qureshi - High liquid savings applicant requesting medical support (Accurately Scored Lower)
  createSampleCase({
    id: 'IAN-2026-1007',
    beneficiaryCode: 'BEN-1007',
    fullName: 'Bilal Qureshi',
    dateOfBirth: '1975-09-14',
    calculatedAge: 51,
    gender: 'Male',
    phone: '+91 98450 99881',
    address: 'Flat 204, Green Heights, Frazer Town',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560005',
    caseType: 'medical',
    title: 'Applicant requesting ₹75,000 for elective knee arthroscopy with substantial personal liquid reserves',
    narrativeDescription:
      '51-year-old applicant requested financial assistance for elective arthroscopic meniscus repair. Household has monthly dependable income of ₹42,000 and ₹3,50,000 in bank fixed deposit savings. Case was assessed to test model invariants: system correctly scores low on financial need and identifies non-priority status, preserving resources for genuinely destitute families.',
    requestedAmount: 75000,
    minimumEffectiveAmount: 50000,
    verifiedRequirement: 75000,
    fundEligibility: ['General Welfare'],
    status: 'Submitted',
    isDemoCase: true,
    createdAt: '2026-09-30T11:00:00Z',
    updatedAt: '2026-10-01T15:00:00Z',
    household: [
      {
        id: 'hh-1',
        name: 'Bilal Qureshi',
        relationship: 'Self',
        age: 51,
        gender: 'Male',
        employmentStatus: 'Employed',
        monthlyIncome: 42000,
        hasDisability: false,
        isDependent: false,
      },
      {
        id: 'hh-2',
        name: 'Sabiha Qureshi',
        relationship: 'Spouse',
        age: 46,
        gender: 'Female',
        employmentStatus: 'Unemployed',
        monthlyIncome: 0,
        hasDisability: false,
        isDependent: true,
      },
    ],
    financial: {
      dependableMonthlyIncome: 42000,
      irregularMonthlyIncome: 5000,
      totalHouseholdIncome: 47000,
      perCapitaIncome: 23500,
      incomeStability: 'highly_stable',
      incomeSources: [
        { id: 'inc-1', source: 'Salaried accountant', amount: 42000, earnerName: 'Bilal Qureshi', isRegular: true },
      ],
      essentialMonthlyExpenses: {
        food: 12000,
        rent: 14000,
        utilities: 2500,
        essentialMedicines: 1000,
        essentialTransport: 3000,
        education: 0,
        caregiving: 0,
        otherEssential: 2000,
        total: 34500,
      },
      liquidAssets: {
        cash: 15000,
        bankBalance: 45000,
        savings: 290000, // total liquid 350,000
        goldSilverValue: 120000,
        investments: 50000,
        totalLiquid: 520000,
      },
      physicalAssets: {
        primaryHomeOwned: false,
        landValue: 0,
        vehiclesValue: 80000,
        livestockValue: 0,
        businessAssets: 0,
        totalPhysical: 80000,
      },
      debtObligations: {
        totalOutstanding: 20000,
        monthlyDebtPayment: 2500,
        debtType: 'Vehicle loan',
        rentArrears: 0,
        medicalDebt: 0,
        utilityArrears: 0,
        foodDebt: 0,
        essentialEducationDebt: 0,
        consequenceOfNonPayment: 'None',
      },
      coverageRatio: 1.21,
      reserveMonths: 15.0,
      debtBurdenRatio: 0.05,
    },
    vulnerability: {
      functionalDisability: {
        hasDisability: false,
        functionalImpact: 'mild',
        requiresCaregiver: false,
        additionalDisabilityExpenses: 0,
      },
      dependencyBurden: {
        totalMembers: 2,
        totalEarners: 1,
        totalDependents: 1,
        childrenCount: 0,
        elderlyCount: 0,
        disabledDependentsCount: 0,
        dependencyRatio: 1.0,
      },
      familyStructure: {
        circumstance: 'stable',
        category: 'intact_family',
      },
      ageVulnerability: {
        primaryBeneficiaryAge: 51,
        lifeStage: 'adult',
        createsVulnerability: false,
      },
      chronicCareSafeguarding: {
        hasChronicIllness: false,
        recurringMedicationNeeds: false,
        monthlyMedicationCost: 0,
        safeguardingRisk: 'none',
        abuseNeglectRisk: false,
        unsafeLivingEnvironment: false,
      },
    },
    deprivation: {
      foodSecurity: { score: 0, mealsPerDay: 3, skippedMeals: false, daysFoodRemaining: 30, childrenAffected: false },
      housingCondition: { score: 0, type: 'adequate', rentArrearsMonths: 0, evictionNoticeReceived: false, overcrowded: false, weatherExposure: false },
      utilitiesAccess: { score: 0, electricityAvailable: true, cleanWaterAvailable: true, cleanCookingFuelAvailable: true, adequateSanitationAvailable: true },
      healthAccess: { score: 0, medicationUnavailable: false, treatmentInterruptedDueToCost: false, inabilityToAffordEssentialCare: false },
      educationDeprivation: { score: 0, childrenOutOfSchool: false, dropoutRiskDueToFees: false, feeArrearsPresent: false, examAdmissionBarrier: false },
      otherBasicNeeds: { score: 0, inadequateClothing: false, inadequateHygieneSanitaryAccess: false, lackEssentialTransport: false, lackCommunicationDevice: false },
    },
    severity: {
      timeUrgency: { timeUntilHarm: 'more_than_3_months', points: 0 },
      consequenceOfNoAssistance: { consequence: 'limited_hardship', points: 1 },
      essentialityOfIntervention: { level: 'helpful_non_essential', points: 1 },
      expectedBenefit: { level: 'meaningful_relief', points: 4 },
      emergencyTrigger: false,
    },
    supportGap: {
      familyCommunitySupport: { level: 'strong_dependable', points: 0 },
      governmentOtherSchemes: { level: 'substantial_scheme_covering_majority', schemesChecked: ['Employer corporate health cover'], points: 0 },
      remainingFundingGap: {
        verifiedTotalNeed: 75000,
        existingAvailableFunds: 50000,
        otherCommittedFunds: 0,
        requestedFromIlAnNoor: 25000,
        minimumEffectiveAmount: 25000,
        gapRatio: 0.33,
        points: 2,
      },
    },
    caseSpecificData: {
      surgeryType: 'Elective Knee Arthroscopy',
    },
    zakat: {
      assessableCashSavings: 350000,
      assessableGoldSilverValue: 120000,
      assessableInvestmentsTradeGoods: 50000,
      deductibleImmediateLiabilities: 20000,
      deductibleBasicMonthlyLivingExpenses: 34500,
      netAssessableWealth: 465500,
      nisabThresholdSilverINR: 58174,
      isBelowNisab: false,
      recipientCategory: 'none',
      preliminaryEligibility: 'Ineligible',
      scholarlyNotes: 'Net assessable wealth (₹4,65,500) significantly exceeds the silver Nisab (₹58,174). Ineligible for Zakat.',
    },
    verification: {
      incomeVerified: true,
      assetsVerified: true,
      householdMembersVerified: true,
      medicalDiagnosisVerified: true,
      costEstimateVerified: true,
      doctorHospitalVerified: true,
      idProofVerified: true,
      addressVerified: true,
      confidenceLevel: 'High',
      verificationNotes: 'Applicant bank statements clearly demonstrate sufficient self-funding capability.',
      inconsistencyFlags: ['Applicant wealth exceeds eligibility thresholds for charitable subsidy.'],
    },
    decisionHistory: [],
  }),
];
